# Timeout in seconds that Limine will use before automatically booting.
timeout: 3

# The entry name that will be displayed in the boot menu.
/GooseOS v1.0
    # We use the Limine boot protocol.
    protocol: limine
    path: boot():/boot/kernel

    # Ramdisk module loading(passed to our kernel by Limine)
    module_path: boot():/boot/ramdisk.img
    module_string: ramdisk
